export enum PAGES {
  LANDING = "/",
  STAFF = "/staff",
  PROJECTS = "/projects",
  USERS = "/users",
  TEAMS = "/teams",
  RESET_PASSWORD = "/reset-password",
  CHANGE_PASSWORD = "/change-password",
  MANAGE = "/manage",
  MANAGE_COHORTS = "/manage/cohorts",
  MANAGE_DEADLINES = "/manage/deadlines",
  MANAGE_USERS = "/manage/users",
  MANAGE_USERS_CSV = "/manage/users-csv",
  MANAGE_TEAMS = "/manage/teams",
  DASHBOARD = "/dashboard",
  DASHBOARD_STUDENT = "/dashboard/student",
  DASHBOARD_ADVISER = "/dashboard/adviser",
  DASHBOARD_MENTOR = "/dashboard/mentor",
  DASHBOARD_ADMINISTRATOR = "/dashboard/administrator",
  SUBMISSIONS = "/submissions",
  ANONYMOUS_SUBMISSIONS = "/submissions/user",
}
