export enum PAGES {
  LANDING = "/",
  STAFF = "/staff",
  PROJECTS = "/projects",
  USERS = "/users",
  RESET_PASSWORD = "/reset-password",
  CHANGE_PASSWORD = "/change-password",
  MANAGE = "/manage",
  MANAGE_ANNOUNCEMENTS = "/manage/announcements",
  MANAGE_ANNOUNCEMENTS_ADD = "/manage/announcements/add",
  MANAGE_COHORTS = "/manage/cohorts",
  MANAGE_DEADLINES = "/manage/deadlines",
  MANAGE_USERS = "/manage/users",
  MANAGE_USERS_CSV = "/manage/users-csv",
  MANAGE_CSV_TEAMS = "/manage/csv-teams",
  MANAGE_CSV_ADVISERS = "/manage/csv-advisers",
  MANAGE_CSV_MENTORS = "/manage/csv-mentors",
  MANAGE_PROJECTS = "/manage/projects",
  ANNOUNCEMENTS = "/announcements",
  DASHBOARD = "/dashboard",
  DASHBOARD_STUDENT = "/dashboard/student",
  DASHBOARD_ADVISER = "/dashboard/adviser",
  DASHBOARD_MENTOR = "/dashboard/mentor",
  DASHBOARD_ADMINISTRATOR = "/dashboard/administrator",
  SUBMISSIONS = "/submissions",
  ANONYMOUS_QUESTIONS_STUDENT = "/submissions/student",
  ANONYMOUS_QUESTIONS_ADVISER = "/submissions/adviser",
}
