export enum PAGES {
  LANDING = "/",
  STAFF = "/staff",
  PROJECTS = "/projects",
  USERS = "/users",
  RESET_PASSWORD = "/reset-password",
  CHANGE_PASSWORD = "/change-password",
  MANAGE = "/manage",
  MANAGE_COHORTS = "/manage/cohorts",
  MANAGE_DEADLINES = "/manage/deadlines",
  MANAGE_USERS = "/manage/users",
  MANAGE_USERS_BATCH_ADD = "/manage/users/batch-add",
  MANAGE_PROJECTS = "/manage/projects",
  DASHBOARD = "/dashboard",
  DASHBOARD_STUDENT = "/dashboard/student",
  DASHBOARD_ADVISER = "/dashboard/adviser",
  DASHBOARD_MENTOR = "/dashboard/mentor",
  DASHBOARD_ADMINISTRATOR = "/dashboard/administrator",
  SUBMISSIONS = "/submissions",
}
