import ExternalVoterGenerationModalItem from "@/components/menus/AddExternalVoterMenuItem/ExternalVoterGenerationModalItem/ExternalVoterGenerationModalItem";
export default ExternalVoterGenerationModalItem;
