import InternalVoterRegistrationModalItem from "@/components/menus/AddInternalVoterMenuItem/InternalVoterRegistrationModalItem/InternalVoterRegistrationModalItem";
export default InternalVoterRegistrationModalItem;
