import ImportInternalVoterCsvModalItem from "@/components/menus/AddInternalVoterMenuItem/ImportInternalVoterCsvModalItem/ImportInternalVoterCsvModalItem";
export default ImportInternalVoterCsvModalItem;
